/**
 * Response envelopes captured from the LIVE backend (server.mjs, port 8080).
 * Every shape here was verified against an actual response body, not the docs.
 */

import type {
  CreditHistoryPoint,
  CreditSnapshot,
  DocumentCatalogItem,
  FrozenFundItem,
  MarketAnalysis,
  MarketDetail,
  NovaStatus,
  OrderDeskConfig,
  StudentNotification,
  StudentTask,
  SupportTicket,
  TasksSummary,
  TradeOrder,
  User,
  WalletTransaction,
} from '../types';

export type {
  CreditHistoryPoint,
  CreditSnapshot,
  DocumentCatalogItem,
  FrozenFundItem,
  MarketAnalysis,
  MarketDetail,
  NovaStatus,
  OrderDeskConfig,
  StudentNotification,
  StudentTask,
  SupportTicket,
  TasksSummary,
  TradeOrder,
  User,
  WalletTransaction,
};

/* ------------------------------------------------------------------ health */

export type HealthResponse = {
  ok: boolean;
  service: string;
  status: string;
  timestamp: string;
  uptime: number;
};

/* ------------------------------------------------------------------ markets */

/** `GET /api/markets` → `{ data: MarketQuote[] }` (no `success` wrapper). */
export type MarketQuote = {
  symbol: string;
  name: string;
  color: string;
  soft: string;
  mark: string;
  stakingApy: number;
  stakingApyLocked: number;
  price: number;
  change: number;
  high: number;
  low: number;
  volume: number;
  rank?: number;
  marketCap?: number | null;
};

export type MarketsResponse = { data: MarketQuote[] };

export type Kline = {
  time: number;
  open: number;
  high: number;
  low: number;
  close: number;
  volume: number;
};

/**
 * `GET /api/market/klines` → `{ data: Kline[], source, pair? }`.
 *
 * VERIFIED: the allowed intervals are exactly `1m | 5m | 15m | 1h`
 * (`allowedIntervals`, server.mjs:16). On a provider failure the backend
 * SYNTHESISES 80 candles and answers `source: 'fallback'`; live Coinbase data
 * answers `source: 'coinbase'`. The UI must disclose which one it is showing.
 */
export type KlineSource = 'coinbase' | 'fallback' | string;

export type KlinesResponse = { data: Kline[]; source?: KlineSource; pair?: string };

export const KLINE_INTERVALS = ['1m', '5m', '15m', '1h'] as const;
export type KlineInterval = (typeof KLINE_INTERVALS)[number];

/** True when the candles were generated by the backend, not fetched live. */
export const isSyntheticKlines = (response: KlinesResponse | null | undefined): boolean =>
  response?.source === 'fallback';

export type MarketDetailResponse = { success: true; market: MarketDetail & MarketQuote };

export type MarketAnalysisResponse = { success: true; analysis: MarketAnalysis } & {
  symbol?: string;
};

export type OhlcvResponse = { success: true; candles: Kline[] };

/* --------------------------------------------------------------------- auth */

export type AuthResponse = {
  success: true;
  message: string;
  user: User;
  token: string;
};

/** `GET /api/auth/me` with no token → anonymous, NOT an error. */
export type MeResponse =
  | { success: true; user: User; anonymous?: false }
  | { success: true; user: null; anonymous: true };

export type AccountResponse = {
  success: true;
  account: {
    id: string;
    username: string;
    name: string;
    email: string;
    phone: string;
    status: string;
    category: string;
    inviteCode: string;
    invitedBy: string;
    invitedByType: string;
    /** Only present when the account registered with an admin code. */
    adminUserCode?: string;
    createdAt: string;
    lastActivityAt: string;
    creditScore: CreditSnapshot;
  };
};

export type ProfileUpdate = {
  name?: string;
  phone?: string;
  preferredCurrency?: 'INR' | 'USDT';
};

/* ------------------------------------------------------------------- wallet */

export type WalletSummary = {
  realBalance: number;
  realUsdtBalance: number;
  frozenBalance: number;
  frozenUsdtBalance: number;
  totalNetRealBalance: number;
  demoBalance: number;
  demoLinked: boolean;
  /** 100 demo credits = 10 INR. */
  conversionRate: number;
  totalConverted: number;
  assetHoldings: Record<string, number>;
  frozenItemsCount: number;
  depositCredited: number;
  depositCreditedUsdt: number;
  creditTotal: number;
  totalBalance: number;
  totalUsdtBalance: number;
  frozenTotal: number;
  frozenTotalUsdt: number;
  openOrders: number;
  /** INR deposits booked but not yet verified. */
  pendingAmount: number;
  pendingAmountUsdt: number;
};

export type WalletSummaryResponse = { success: true; summary: WalletSummary };
export type TransactionsResponse = { success: true; transactions: WalletTransaction[] };
/**
 * `GET /api/wallet/frozen` → `{ success, frozenBalance, frozenUsdtBalance, items }`.
 * VERIFIED against a live response: the array key is `items`, not `frozen`.
 */
export type FrozenResponse = {
  success: true;
  frozenBalance: number;
  frozenUsdtBalance: number;
  items: FrozenFundItem[];
};

export type ReleaseResponse = {
  success: true;
  message: string;
  releasedAmount: number;
  newRealBalance: number;
  newFrozenBalance: number;
};

/* ------------------------------------------------------------------ deposit */

export type DepositSubmitResponse = {
  success: true;
  message: string;
  depositId: string;
  amount: number;
  currency: 'INR' | 'USDT';
  status: 'processing';
  newFrozenBalance: number;
};

export type DepositRail = 'inr' | 'usdt';

/* -------------------------------------------------------- withdrawal (S1) */

/** Chosen path: `/api/withdrawal/support` — files a ticket, does NOT debit. */
export type WithdrawalSupportResponse = {
  success: true;
  message: string;
  ticket: SupportTicket;
};

/* ------------------------------------------------------------------- orders */

/** Wallet snapshot embedded in order responses, so one call refreshes both. */
export type OrderWalletSnapshot = {
  realBalance: number;
  realUsdtBalance: number;
  frozenBalance: number;
  frozenUsdtBalance: number;
  totalBalance: number;
  totalUsdtBalance: number;
  creditTotal: number;
  depositCredited: number;
  openOrders?: number;
};

export type OrderCreateResponse = {
  success: true;
  message: string;
  orderId: string;
  order: TradeOrder;
  status: TradeOrder['status'];
  newDemoBalance?: number;
  newRealBalance?: number;
  wallet?: OrderWalletSnapshot;
};

export type OrderListResponse = {
  success: true;
  orders: TradeOrder[];
  total: number;
  wallet?: OrderWalletSnapshot;
};

export type OrderStatusResponse = {
  success: true;
  order: TradeOrder;
  status: TradeOrder['status'];
} & Record<string, unknown>;

export type OrderCreateInput = {
  symbol: string;
  side: 'up' | 'down';
  amount: number;
  currency: 'INR' | 'USDT';
  accountType: 'real' | 'demo';
  durationSeconds: number;
  payoutPercent: number;
};

/* ------------------------------------------------------------- desk config */

export type OrderConfigResponse = { success: true; config: OrderDeskConfig };

/* ----------------------------------------------------------------- staking */

export type StakeResponse = {
  success: true;
  message: string;
  /** Pass this id to `/api/wallet/frozen/release` to unstake. */
  vaultId: string;
  newAvailable: number;
  newFrozen: number;
};

/* ------------------------------------------------------------------- tasks */

export type TasksResponse = {
  success: true;
  tasks: StudentTask[];
  summary: TasksSummary;
};

/* ------------------------------------------------------------- credit score */

export type CreditScoreResponse = {
  success: true;
  creditScore: CreditSnapshot & { category?: string };
};

export type CreditHistoryResponse = { success: true; history: CreditHistoryPoint[] };

/* ----------------------------------------------------------- notifications */

export type NotificationsResponse = {
  success: true;
  notifications: StudentNotification[];
  /** VERIFIED: the backend hardcodes this to 0. Never bind a badge to it. */
  unread: number;
};

/* ----------------------------------------------------------------- support */

export type SupportListResponse = {
  success: true;
  tickets: SupportTicket[];
  categories: string[];
};

export type SupportCreateResponse = {
  success: true;
  message: string;
  ticket: SupportTicket;
};

/* --------------------------------------------------------------- documents */

export type DocumentsResponse = { success: true; documents: DocumentCatalogItem[] };

export type StatementResponse = {
  success: true;
  statement: {
    statementId: string;
    generatedAt: string;
    accountHolder: {
      name: string;
      email: string;
      phone: string;
      registeredAt: string;
      inviteCode: string;
    };
    balances: {
      realBalance: number;
      realUsdtBalance: number;
      frozenBalance: number;
      frozenUsdtBalance: number;
      demoBalance: number;
      totalRealBalance: number;
      totalUsdtBalance: number;
      totalConverted: number;
    };
    frozenItems: FrozenFundItem[];
    transactions: WalletTransaction[];
  };
};

export type ProofResponse = {
  success: true;
  proof: {
    proofId: string;
    issuedAt: string;
    validUntil: string;
    platform: string;
    accountHolder: {
      name: string;
      email: string;
      phone: string;
      registeredAt: string;
      inviteCode: string;
    };
    status?: string;
    balances?: Record<string, number>;
  };
};

export type AgreementResponse = {
  success: true;
  agreement: {
    agreementId?: string;
    type?: string;
    title?: string;
    issuedAt?: string;
    party?: { name: string; email: string };
    clauses?: Array<{ heading?: string; title?: string; body?: string; text?: string }>;
    sections?: Array<{ heading?: string; title?: string; body?: string; text?: string }>;
  };
};

export type InvoiceResponse = {
  success: true;
  invoice: {
    invoiceId: string;
    issuedAt: string;
    periodStart: string;
    periodEnd: string;
    billTo: {
      name: string;
      email: string;
      phone: string;
      userId: string;
      inviteCode: string;
    };
    items: Array<Record<string, unknown>>;
    totals: {
      subtotalInr: number;
      subtotalUsdt?: number;
      totalInr?: number;
      totalUsdt?: number;
    };
  };
};

/* -------------------------------------------------------------------- nova */

export type NovaStatusResponse = { success: true; nova: NovaStatus };

export type NovaChatResponse = {
  success: true;
  reply: string;
  sources?: string[];
  intent?: string;
  nova?: NovaStatus;
};
