import { useState, type FormEvent } from 'react';
import { Link } from 'react-router-dom';
import {
  ArrowDownLeft, ArrowRight, ArrowUpRight, Bell, BookOpen, Check, ChevronRight, CircleHelp,
  Copy, CreditCard, ExternalLink, Globe2, Headphones, KeyRound, LockKeyhole, MessageCircle,
  MessagesSquare, Plus, Search, Settings, ShieldCheck, Sparkles, User, Users, Wallet as WalletIcon,
} from 'lucide-react';
import { CoinIcon, EmptyState, PageHero } from './components';
import { useApp } from './app-context';
import { INR_RATE, money } from './data';
import { useMarket } from './market-context';

const TELEGRAM_URL = import.meta.env.VITE_TELEGRAM_URL || 'https://t.me/mudrexxearn_support';

export function ProfilePage() {
  const { user, openAuth, notify } = useApp();
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); notify('Settings saved', 'Your profile preferences have been updated.'); };
  return <main><PageHero eyebrow="Your account" title="Profile settings" copy="Keep your personal details, preferences, and security controls up to date." /><section className="container account-layout"><AccountNav active="profile" /><div className="settings-content">{!user ? <EmptyState title="Sign in to view your profile" copy="Your settings will appear here after you securely sign in." action={<button className="btn btn-purple" onClick={() => openAuth('signin')}>Sign in <ArrowRight /></button>} /> : <><div className="settings-card profile-intro"><span className="large-avatar">{user.name.slice(0,1).toUpperCase()}</span><div><h2>{user.name}</h2><p>{user.email}</p><span><Check /> Demo profile active</span></div><button className="btn btn-soft">Change photo</button></div><form className="settings-card settings-form" onSubmit={submit}><div className="card-heading"><div><h3>Personal information</h3><p>Used for your profile and support requests.</p></div><User /></div><div className="two-fields"><label><span>Full name</span><input defaultValue={user.name} required /></label><label><span>Email address</span><input defaultValue={user.email} type="email" required /></label><label><span>Mobile number</span><input placeholder="+91 98765 43210" /></label><label><span>Preferred currency</span><select defaultValue="INR"><option>INR</option><option>USDT</option></select></label></div><button className="btn btn-purple">Save changes</button></form><div className="settings-card security-settings"><div className="card-heading"><div><h3>Security</h3><p>Additional protection for your account.</p></div><ShieldCheck /></div><SettingRow icon={<KeyRound />} title="Password" copy="Last changed recently" action="Change" /><SettingRow icon={<LockKeyhole />} title="Two-factor authentication" copy="Add an authenticator app" action="Set up" /><SettingRow icon={<Bell />} title="Login alerts" copy="Email alerts for new sessions" action="Enabled" /></div></>}</div></section></main>;
}

export function WalletPage() {
  const { user, openAuth } = useApp();
  const { quotes } = useMarket();
  return <main><PageHero eyebrow="Your account" title="Wallet" copy="A clear view of balances, activity, and funding options." /><section className="container account-layout"><AccountNav active="wallet" /><div className="settings-content">{!user ? <EmptyState title="Your wallet is waiting" copy="Sign in to see balances and recent activity." action={<button className="btn btn-purple" onClick={() => openAuth('signin')}>Sign in <ArrowRight /></button>} /> : <><div className="wallet-balance-card"><span>Total balance <small>Demo portfolio</small></span><h2>₹1,24,892.40</h2><p><ArrowUpRight /> +₹2,841.20 (2.33%) today</p><div><Link className="btn btn-white" to="/deposit"><Plus /> Deposit</Link><Link className="btn btn-glass" to="/instant-order"><ArrowUpRight /> Trade</Link><button className="btn btn-glass"><ArrowDownLeft /> Withdraw</button></div></div><div className="settings-card"><div className="card-heading"><div><h3>Your assets</h3><p>Illustrative balances for this experience.</p></div><WalletIcon /></div><div className="wallet-assets">{quotes.slice(0,4).map((quote, index) => { const quantities = [0.0084, .72, 2.1, 12.4]; const value = quantities[index] * quote.price * INR_RATE; return <div key={quote.symbol}><CoinIcon asset={quote} /><span><strong>{quote.name}</strong><small>{quantities[index]} {quote.symbol}</small></span><b>{money(value, 'INR')}<small className={quote.change >= 0 ? 'up' : 'down'}>{quote.change >= 0 ? '+' : ''}{quote.change.toFixed(2)}%</small></b><ChevronRight /></div>; })}</div></div><div className="settings-card"><div className="card-heading"><div><h3>Recent activity</h3><p>Your latest wallet events.</p></div><CreditCard /></div><div className="activity-list"><ActivityRow icon={<ArrowDownLeft />} title="INR deposit" time="Today · 10:42 AM" value="+₹5,000" tone="up" /><ActivityRow icon={<Sparkles />} title="Demo reward" time="Yesterday · 6:18 PM" value="+120 credits" tone="up" /><ActivityRow icon={<ArrowUpRight />} title="BTC order preview" time="Yesterday · 2:04 PM" value="₹1,000" /></div></div></>}</div></section></main>;
}

export function SupportPage() {
  const [query, setQuery] = useState('');
  const faqs = ['How do INR deposits work?', 'Which network should I use for USDT?', 'How are live prices calculated?', 'How can I secure my account?'];
  return <main><PageHero eyebrow="We’re here to help" title="How can we support you?" copy="Browse answers or reach the support team on Telegram."><label className="support-search"><Search /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search for an answer" /></label></PageHero><section className="container support-content"><div className="support-actions"><a href={TELEGRAM_URL} target="_blank" rel="noreferrer"><span className="support-action-icon telegram"><MessageCircle /></span><div><small>FASTEST RESPONSE</small><h3>Chat on Telegram</h3><p>Connect with our support channel for account and product help.</p><b>Open Telegram <ExternalLink /></b></div></a><article><span className="support-action-icon"><MessagesSquare /></span><div><small>HELP CENTRE</small><h3>Browse quick answers</h3><p>Find guidance on funding, markets, account security, and more.</p><b>View articles <ArrowRight /></b></div></article><article><span className="support-action-icon mint"><Headphones /></span><div><small>ACCOUNT HELP</small><h3>Raise a request</h3><p>Sign in and share the details. Never include a password or recovery phrase.</p><b>Create request <ArrowRight /></b></div></article></div><div className="faq-card"><div className="card-heading"><div><h3>Frequently asked questions</h3><p>Answers to common questions from the community.</p></div><CircleHelp /></div>{faqs.filter((item) => item.toLowerCase().includes(query.toLowerCase())).map((item) => <details key={item}><summary>{item}<Plus /></summary><p>This demo experience shows the complete interface. Connect your verified payment, custody, and support providers before a production launch.</p></details>)}</div><div className="safety-callout"><ShieldCheck /><div><strong>Support will never ask for your OTP or seed phrase.</strong><p>Only use links shown inside the application and verify Telegram handles before starting a conversation.</p></div></div></section></main>;
}

export function CommunityPage() {
  return <main><PageHero eyebrow="Mudrexx community" title="Learn together. Grow together." copy="Join market conversations, practical learning sessions, and product updates." /><section className="container community-content"><div className="community-feature"><div><span className="eyebrow eyebrow-light">COMMUNITY SPOTLIGHT</span><h2>Crypto feels clearer when no one learns alone.</h2><p>Get weekly market explainers, security tips, and live product walkthroughs—without hype or guaranteed-return claims.</p><a className="btn btn-white btn-lg" href={TELEGRAM_URL} target="_blank" rel="noreferrer">Join on Telegram <ExternalLink /></a></div><div className="community-orbit"><span><Users /></span><i/><i/><i/><b>12K<small>learning moments</small></b></div></div><div className="community-grid"><CommunityCard icon={<BookOpen />} label="LEARN" title="Market basics" copy="Short, practical explainers for spot, futures scenarios, staking, and wallet safety." /><CommunityCard icon={<Globe2 />} label="CONNECT" title="Weekly office hours" copy="Bring questions and learn how product features work with a guided walkthrough." /><CommunityCard icon={<ShieldCheck />} label="STAY SAFE" title="Security watch" copy="Recognise impersonation, phishing, and promises that sound too good to be true." /></div><div className="community-guidelines"><div><h3>Built for useful conversations</h3><p>Our community principles keep every space respectful and practical.</p></div>{['No guaranteed-return claims', 'No unsolicited direct messages', 'Never share account secrets', 'Respect every learning level'].map((item) => <span key={item}><Check />{item}</span>)}</div></section></main>;
}

function AccountNav({ active }: { active: 'profile' | 'wallet' }) { return <aside className="account-nav"><span>ACCOUNT</span><Link className={active === 'profile' ? 'active' : ''} to="/profile"><Settings /> Profile settings <ChevronRight /></Link><Link className={active === 'wallet' ? 'active' : ''} to="/wallet"><WalletIcon /> Wallet <ChevronRight /></Link><Link to="/support"><Headphones /> Support <ChevronRight /></Link><Link to="/community"><Users /> Community <ChevronRight /></Link><div><ShieldCheck /><p><strong>Security tip</strong>Enable two-factor authentication before funding your account.</p></div></aside>; }
function SettingRow({ icon, title, copy, action }: { icon: React.ReactNode; title: string; copy: string; action: string }) { return <div className="setting-row"><span>{icon}</span><div><strong>{title}</strong><small>{copy}</small></div><button>{action} <ChevronRight /></button></div>; }
function ActivityRow({ icon, title, time, value, tone = '' }: { icon: React.ReactNode; title: string; time: string; value: string; tone?: string }) { return <div><span>{icon}</span><div><strong>{title}</strong><small>{time}</small></div><b className={tone}>{value}</b></div>; }
function CommunityCard({ icon, label, title, copy }: { icon: React.ReactNode; label: string; title: string; copy: string }) { return <article><span>{icon}</span><small>{label}</small><h3>{title}</h3><p>{copy}</p><button>Explore <ArrowRight /></button></article>; }
